server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: clientModule
          uri: lb://client
          predicates:
            - Path=/client/**
        - id: departmentModule
          uri: lb://department
          predicates:
            - Path=/department/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
